### ISSUE TITLE
Update the angular material to 0.10.x version.

### ISSUE THREAD

**Issue by piyushchauhan2011** [Toilal/angular-material-components#5]
I want to use the datepicker from the components but the repository is incompatible with material 0.10 and breaks the app.

**Comment by piyushchauhan2011** [comment]
Is this repository active ??

**Comment by Toilal** [comment]
Sorry, was busy those days, can now on vacations feel free to fork and open
a pull request.
Le 10 juil. 2015 08:11, "Piyush Chauhan" <notifications@github.com> a
écrit :

**Comment by piyushchauhan2011** [comment]
Cool :smile:

**Comment by Toilal** [comment]
I've just perform the upgrade to all latest versions (material 0.10 and angular 1.4.3), and it works without any changes...

I'll push packaging and demo changes.

**Comment by piyushchauhan2011** [comment]
:+1:
